# Generated by Django 4.1.3 on 2022-12-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='courses',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
    ]
