# Generated by Django 4.1.3 on 2022-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_created_at_courses_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'num'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='courseteachers',
            old_name='first_name',
            new_name='name_first',
        ),
        migrations.RenameField(
            model_name='courseteachers',
            old_name='last_name',
            new_name='name_second',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='day_birth',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='num',
            field=models.PositiveIntegerField(verbose_name='Lesson number'),
        ),
    ]
